sudo: required
language: python
services:
  - docker

before_install:
  - pip install travis-sphinx
  - docker pull scannerresearch/scanner:cpu

script:
  - docker run -w /app -v $(pwd):/app -d scannerresearch/scanner:cpu ./travis.sh

after_success:
  - travis-sphinx deploy
