language: python
python:
  - "3.5"

sudo: required
services:
  - docker

env:
  secure: "M+N4gEsYsiF+zfFBSG7bvpmKNOff+c0uX1dUZ9/rFoBro7Lftsq3FvGuLMvfb9gzuNcWH9vSKf9fmUI6apeBxgVqFIzn/LiNhbdrVzg8P2IRtZ2GSDOmzyp0HDzL/bET8FncQLccKCG3Il3QmGstBTJ3cpxJqJ1O60CsnKGX+UlYr51yz53hPBETbgLsEFTNFXVifvgrKJumfBqjx2QdqkYTUQO6JjYbcUo3rlgqA6eSluCY/DgSB0xzaznB8XbdJkIi7B98E/zmxM6uJKAYXNR/Srv+jbcryjW9GXldYHbQad06O1bKK12UPnrCKIVVg9iHd/Mx7S9eqeueGOMAfozIAcGG+oOV/5PIcvVlUeyQY8ATHx7GFYvmegUqoFIX3Ph5o4v12997rmzhaLag0qigOtZ6O3/Dg79BMbFyTdYz7LzHlmZ64ST3D/MRK76Hl73g4xSnUBNah3wysljPLcWn2WG+fAoRJ8ArwApJN85UWj+s9OPFjapxfGBNykYOoSTqEKspK+pbCUrPWY6yEDtTjUoTnyfKLSxQiCw/n4Hnxk7NqTAwLga441fymljgk3svdBTSnx00RP50SIRjm0HdGhO9XOWM04ba48nGHnLlpIlqPmFNaqFXlwePXu7UZOMYzJmxfksj5XlX4HZA8G3LoUBaD8GJm3D0z/6jkrg=" # PYPI_PASS

before_install:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - pip3 install travis-sphinx
  - docker pull scannerresearch/scanner:cpu-latest

script: docker run -w /app -v $(pwd):/app scannerresearch/scanner:cpu-latest ./scripts/travis-build.sh

after_success: ./scripts/travis-publish.sh
