language: python
python:
  - "3.5"

sudo: required
services:
  - docker

before_install:
  - export LC_ALL=C.UTF-8
  - export LANG=C.UTF-8
  - pip3 install travis-sphinx
  - docker pull scannerresearch/scanner:cpu

script:
  - docker run -w /app -v $(pwd):/app scannerresearch/scanner:cpu ./travis.sh

after_success:
  - travis-sphinx deploy
